{% set name = "napari-annotation-project" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 247725577d3aade19442c4f958895f0a2d19709501dc903ccbc93a7ed0cfc2f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - numpy
    - python >={{ python_min }}
    - pyyaml
    - qtpy
    - scikit-image

test:
  imports:
    - napari_annotation_project
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-annotation-project
  summary: A napari plugin to keep images and annotations as a re-loadable project
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/guiwitz/napari-annotation-project

extra:
  recipe-maintainers:
    - goanpeca
    - guiwitz
    - jaimergp
